In [1]:
import nltk

In [2]:
paragraph="""John does his work intelligently
           John is an intelligent man
           John is always working"""

In [3]:
sentences=nltk.sent_tokenize(paragraph)

In [4]:
print(sentences)

['John does his work intelligently\n           John is an intelligent man\n           John is always working']


In [5]:
words=nltk.word_tokenize(paragraph)

In [6]:
print(words)

['John', 'does', 'his', 'work', 'intelligently', 'John', 'is', 'an', 'intelligent', 'man', 'John', 'is', 'always', 'working']


In [7]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [8]:
sentences=nltk.sent_tokenize(paragraph)
Stemmer=PorterStemmer()

In [9]:
for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[Stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words)

In [10]:
print(sentences)

['john work intellig john intellig man john alway work']


In [11]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [12]:
sentences=nltk.sent_tokenize(paragraph)
lemmatizer=WordNetLemmatizer()
print(sentences)

['John does his work intelligently\n           John is an intelligent man\n           John is always working']


In [13]:
for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words)

In [14]:
print(sentences)

['John work intelligently John intelligent man John always working']


In [15]:
#cloning the text
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [44]:
ps=PorterStemmer()
wordnet=WordNetLemmatizer()
sentences=nltk.sent_tokenize(paragraph)
corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[i])
    review=review.lower()
    review=review.split()
    for word in review:
            if not word in set(stopwords.words('english')):
                    review=ps.stem(word) 
                    corpus.append(review)
print(corpus)

['john', 'work', 'intellig', 'john', 'intellig', 'man', 'john', 'alway', 'work']


In [46]:
ps=PorterStemmer()
wordnet=WordNetLemmatizer()
sentences=nltk.sent_tokenize(paragraph)
corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[i])
    review=review.lower()
    review=review.split() 
    for word in review:
            if not word in set(stopwords.words('english')):
                review=wordnet.lemmatize(word)
                corpus.append(review)
print(corpus)

['john', 'work', 'intelligently', 'john', 'intelligent', 'man', 'john', 'always', 'working']


In [43]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
print(cv)
x=cv.fit_transform(corpus).toarray()
print(x)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)
[[0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]]


In [45]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
print(cv)
x=cv.fit_transform(corpus).toarray()
print(x)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)
[[0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]]


In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer()
print(cv)
x=cv.fit_transform(corpus).toarray()
print(x)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)
[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
